# Generated by Django 6.0.1 on 2026-01-09 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='colaboradores/fotos/')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FERIAS', 'Ferias'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracoes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ContratoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('prazo_inicial', models.IntegerField()),
                ('data_fim_inicial', models.DateField()),
                ('prorrogacao', models.IntegerField(blank=True, null=True)),
                ('data_fim_prorrogacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('PRORROGADO', 'Prorrogado'), ('EFETIVADO', 'Efetivado'), ('ENCERRADO', 'Encerrado')], default='VIGENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_experiencia', to='colaboradores.colaborador')),
            ],
            options={
                'db_table': 'contratos_experiencia',
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='colaboradores.colaborador')),
            ],
            options={
                'db_table': 'dependentes',
            },
        ),
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('nome_arquivo_original', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo', models.FileField(upload_to='colaboradores/documentos/')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='colaboradores.colaborador')),
            ],
            options={
                'db_table': 'documentos_colaborador',
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='colaboradores.empresa'),
        ),
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('motivo_desligamento', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pode_recontratar', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocklist', to='colaboradores.empresa')),
            ],
            options={
                'db_table': 'blocklist',
            },
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_aquisitivo_inicio', models.DateField()),
                ('periodo_aquisitivo_fim', models.DateField()),
                ('periodo_concessivo_limite', models.DateField()),
                ('dias_direito', models.IntegerField(default=30)),
                ('dias_gozados', models.IntegerField(default=0)),
                ('dias_vendidos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROGRAMADA', 'Programada'), ('EM_GOZO', 'Em Gozo'), ('CONCLUIDA', 'Concluida'), ('VENCIDA', 'Vencida')], default='PENDENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='colaboradores.colaborador')),
            ],
            options={
                'db_table': 'ferias',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='colaboradores.colaborador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_alteracoes',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='colaboradores.colaborador')),
            ],
            options={
                'db_table': 'localizacoes',
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('entidade_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('entidade_id', models.IntegerField(blank=True, null=True)),
                ('entidade_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_sistema',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('operador', 'Operador'), ('visualizador', 'Visualizador')], default='operador', max_length=20)),
                ('pergunta_seguranca', models.CharField(blank=True, max_length=255, null=True)),
                ('resposta_seguranca', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfis_usuario',
            },
        ),
        migrations.CreateModel(
            name='PeriodoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias', models.IntegerField()),
                ('abono_pecuniario', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ferias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='colaboradores.ferias')),
            ],
            options={
                'db_table': 'periodos_ferias',
            },
        ),
    ]
