# Generated by Django 6.0.1 on 2026-01-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_agencia_colaborador_am_valor_desconto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocklist',
            options={'verbose_name': 'Block-List', 'verbose_name_plural': 'Block-List'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='contratoexperiencia',
            options={'verbose_name': 'Contrato de Experiência', 'verbose_name_plural': 'Contratos de Experiência'},
        ),
        migrations.AlterModelOptions(
            name='dependente',
            options={'verbose_name': 'Dependente', 'verbose_name_plural': 'Dependentes'},
        ),
        migrations.AlterModelOptions(
            name='documentocolaborador',
            options={'verbose_name': 'Documento do Colaborador', 'verbose_name_plural': 'Documentos do Colaborador'},
        ),
        migrations.AlterModelOptions(
            name='ferias',
            options={'verbose_name': 'Férias', 'verbose_name_plural': 'Férias'},
        ),
        migrations.AlterModelOptions(
            name='historicoalteracao',
            options={'ordering': ['-data_alteracao'], 'verbose_name': 'Histórico de Alteração', 'verbose_name_plural': 'Histórico de Alterações'},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
        migrations.AlterModelOptions(
            name='logsistema',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Log do Sistema', 'verbose_name_plural': 'Logs do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterModelOptions(
            name='periodoferias',
            options={'verbose_name': 'Período de Férias', 'verbose_name_plural': 'Períodos de Férias'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='adiantamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cnpj_ultimo_emprego',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='conselho_regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf_mae',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf_pai',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_admissao_ultimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_casamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_exame_medico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_inativacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_pagamento_adiantamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_saida_ultimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_ultima_contribuicao_sindical',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='deficiencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='dias_folga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='empresa_ultimo_emprego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula_ultimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo_inativacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_medico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero_conselho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='observacoes_banco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='observacoes_contrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='observacoes_desligamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='percentual_adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='primeiro_registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='regiao_conselho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='seguro_vida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sigla_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='submotivo_inativacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sv_valor_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_exames',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf_crm',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='va_percentual_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vr_percentual_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROGRAMADA', 'Programada'), ('EM_GOZO', 'Em Gozo'), ('CONCLUIDA', 'Concluída'), ('VENCIDA', 'Vencida')], default='PENDENTE', max_length=20),
        ),
    ]
